# Generated by Django 6.1.1 on 2026-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preferred_education',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
