# Generated by Django 6.1.1 on 2026-09-26 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated, e.g. Python, SQL, React')),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('links', models.TextField(blank=True, help_text='One URL per line')),
                ('commute_radius', models.PositiveIntegerField(default=10)),
                ('show_email', models.BooleanField(default=False)),
                ('show_experience', models.BooleanField(default=True)),
                ('is_visible_to_recruiters', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
